#!/usr/bin/env python3
"""Cross-platform LaTeX build driver for the competition paper.

This file is intentionally dependency-free. Makefile and make.ps1 delegate to it
so Linux and Windows follow the same build semantics.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Iterable

ROOT = Path(__file__).resolve().parent
BUILD = ROOT / "build"
GENERATED = BUILD / "_generated"
PROFILES = ROOT / "profiles"

TARGETS = ("draft", "review", "release", "print")


class BuildError(RuntimeError):
    pass


def _safe_name(value: str, what: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9._-]+", value):
        raise BuildError(f"invalid {what}: {value!r}")
    return value


def load_profile(name: str) -> dict:
    _safe_name(name, "profile")
    profile_path = PROFILES / f"{name}.json"
    if not profile_path.is_file():
        available = ", ".join(sorted(p.stem for p in PROFILES.glob("*.json")))
        raise BuildError(
            f"profile {name!r} not found at {profile_path}. "
            f"Available profiles: {available or '(none)'}"
        )

    try:
        cfg = json.loads(profile_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BuildError(f"cannot read profile {profile_path}: {exc}") from exc

    entrypoint = cfg.get("entrypoint")
    if not isinstance(entrypoint, str) or not entrypoint.strip():
        raise BuildError(f"profile {name!r} must define a non-empty 'entrypoint'")

    required = cfg.get("required_files", [])
    if not isinstance(required, list) or not all(isinstance(x, str) for x in required):
        raise BuildError(f"profile {name!r} has invalid 'required_files'")

    for rel in required:
        path = (ROOT / rel).resolve()
        try:
            path.relative_to(ROOT.resolve())
        except ValueError as exc:
            raise BuildError(f"profile required file escapes paper/latex: {rel}") from exc
        if not path.exists():
            raise BuildError(
                f"profile {name!r} is not ready: required file is missing: {rel}"
            )

    entry = (ROOT / entrypoint).resolve()
    try:
        entry.relative_to(ROOT.resolve())
    except ValueError as exc:
        raise BuildError(f"profile entrypoint escapes paper/latex: {entrypoint}") from exc
    if not entry.is_file():
        raise BuildError(f"profile entrypoint does not exist: {entrypoint}")

    cfg["_entrypoint_path"] = entry
    cfg["_profile_path"] = profile_path
    return cfg


def _which(executable: str) -> str:
    found = shutil.which(executable)
    if not found:
        raise BuildError(f"required executable was not found in PATH: {executable}")
    return found


def _display_cmd(cmd: Iterable[str]) -> str:
    def q(x: str) -> str:
        return f'"{x}"' if any(c.isspace() for c in x) else x
    return " ".join(q(str(x)) for x in cmd)


def run(cmd: list[str], timeout: int, cwd: Path = ROOT) -> None:
    print(f"+ {_display_cmd(cmd)}")
    try:
        completed = subprocess.run(
            cmd,
            cwd=str(cwd),
            check=False,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as exc:
        raise BuildError(
            f"command exceeded {timeout}s timeout: {_display_cmd(cmd)}"
        ) from exc
    except OSError as exc:
        raise BuildError(f"failed to start command: {_display_cmd(cmd)}: {exc}") from exc

    if completed.returncode != 0:
        raise BuildError(
            f"command failed with exit code {completed.returncode}: {_display_cmd(cmd)}"
        )


def clean_target(target: str) -> None:
    BUILD.mkdir(parents=True, exist_ok=True)
    for path in BUILD.glob(f"{target}.*"):
        if path.is_file() or path.is_symlink():
            path.unlink()
        elif path.is_dir():
            shutil.rmtree(path)


def make_wrapper(target: str, profile_name: str, entrypoint: Path) -> Path:
    GENERATED.mkdir(parents=True, exist_ok=True)
    entry_rel = entrypoint.relative_to(ROOT).as_posix()
    wrapper = GENERATED / f"{target}.tex"
    wrapper.write_text(
        "% AUTO-GENERATED by build.py. Do not edit.\n"
        f"\\def\\PaperBuildMode{{{target}}}\n"
        f"\\def\\PaperProfileName{{{profile_name}}}\n"
        f"\\input{{{entry_rel}}}\n",
        encoding="utf-8",
    )
    return wrapper


def latex_command(engine: str, target: str, wrapper: Path) -> list[str]:
    return [
        engine,
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        f"-jobname={target}",
        f"-output-directory={BUILD.as_posix()}",
        wrapper.relative_to(ROOT).as_posix(),
    ]


def detect_bibliography(target: str) -> str | None:
    bcf = BUILD / f"{target}.bcf"
    if bcf.is_file():
        return "biber"

    aux = BUILD / f"{target}.aux"
    if aux.is_file():
        text = aux.read_text(encoding="utf-8", errors="ignore")
        if "\\bibdata{" in text:
            return "bibtex"

    return None


def run_bibliography(kind: str, target: str, timeout: int) -> None:
    if kind == "biber":
        biber = _which("biber")
        run(
            [
                biber,
                "--input-directory",
                BUILD.as_posix(),
                "--output-directory",
                BUILD.as_posix(),
                target,
            ],
            timeout=timeout,
        )
        return

    if kind == "bibtex":
        bibtex = _which("bibtex")
        # Running from the LaTeX root lets BibTeX resolve references.bib in this
        # directory while still writing target.bbl next to build/target.aux.
        run([bibtex, f"build/{target}"], timeout=timeout)
        return

    raise BuildError(f"unsupported bibliography backend: {kind}")


def validate_pdf(target: str) -> Path:
    pdf = BUILD / f"{target}.pdf"
    if not pdf.is_file():
        raise BuildError(f"expected output was not created: {pdf}")
    if pdf.stat().st_size < 1024:
        raise BuildError(f"output PDF is unexpectedly small: {pdf} ({pdf.stat().st_size} bytes)")
    return pdf


def build_one(target: str, profile_name: str, engine_override: str | None, timeout: int) -> Path:
    if target not in TARGETS:
        raise BuildError(f"unsupported target: {target}")

    cfg = load_profile(profile_name)
    engine = engine_override or cfg.get("engine") or "xelatex"
    engine = _safe_name(str(engine), "engine")
    engine_path = _which(engine)

    clean_target(target)
    wrapper = make_wrapper(target, profile_name, cfg["_entrypoint_path"])
    cmd = latex_command(engine_path, target, wrapper)

    print(f"== build target={target} profile={profile_name} engine={engine} ==")

    try:
        # First pass determines bibliography requirements.
        run(cmd, timeout=timeout)
        bib_kind = detect_bibliography(target)

        if bib_kind:
            print(f"bibliography backend detected: {bib_kind}")
            run_bibliography(bib_kind, target, timeout)
            # Two passes after bibliography settle citations and cross references.
            run(cmd, timeout=timeout)
            run(cmd, timeout=timeout)
        else:
            # Second pass settles ordinary cross references.
            run(cmd, timeout=timeout)

        pdf = validate_pdf(target)
    except BuildError:
        # XeLaTeX may leave a partial PDF even when it exits non-zero. Never let
        # that file masquerade as a successfully built competition artifact.
        partial_pdf = BUILD / f"{target}.pdf"
        if partial_pdf.exists():
            partial_pdf.unlink()
        raise

    print(f"OK: {pdf.relative_to(ROOT)} ({pdf.stat().st_size} bytes)")
    return pdf


def clean_all() -> None:
    BUILD.mkdir(parents=True, exist_ok=True)
    for child in BUILD.iterdir():
        if child.name == ".gitkeep":
            continue
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()
    print(f"cleaned: {BUILD}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build competition paper with strict, cross-platform semantics."
    )
    parser.add_argument(
        "target",
        choices=(*TARGETS, "all", "clean"),
        nargs="?",
        default="draft",
    )
    parser.add_argument(
        "--profile",
        default=os.environ.get("PAPER_PROFILE", "generic"),
        help="profile name under profiles/<name>.json (default: generic)",
    )
    parser.add_argument(
        "--engine",
        default=os.environ.get("PAPER_TEX_ENGINE"),
        help="override TeX engine declared by profile",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=int(os.environ.get("PAPER_BUILD_TIMEOUT", "180")),
        help="timeout in seconds for each external command (default: 180)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.timeout <= 0:
        print("ERROR: --timeout must be positive", file=sys.stderr)
        return 2

    try:
        if args.target == "clean":
            clean_all()
            return 0

        if args.target == "all":
            for target in TARGETS:
                build_one(target, args.profile, args.engine, args.timeout)
            return 0

        build_one(args.target, args.profile, args.engine, args.timeout)
        return 0

    except BuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
